name: Build, Test, and Deploy

on:
  push:
    branches:
      - develop
      - Task3
  pull_request:
    branches:
      - develop
      - Task3

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Checkout репозиторій
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Встановлення .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    # 3. Встановлення arduino-cli вручну для Windows
    - name: Install arduino-cli
      run: |
        # Завантажуємо архів з Arduino CLI
        Invoke-WebRequest -Uri https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Windows_64bit.zip -OutFile arduino-cli.zip
        
        # Розпаковуємо архів в директорію
        Expand-Archive arduino-cli.zip -DestinationPath C:\arduino-cli
        
        # Додаємо шлях до Arduino CLI в PATH
        echo "::add-path::C:\arduino-cli"

    # 4. Налаштування Arduino CLI
    - name: Configure Arduino CLI
      run: |
        # Перевіряємо, чи Arduino CLI доступний
        arduino-cli version

        # Оновлюємо індекс ядер
        arduino-cli core update-index

        # Встановлюємо платформу для Arduino
        arduino-cli core install arduino:avr

    # 5. Компіляція прошивки
    - name: Check file path
      run: |
        echo "Checking if file exists:"
        dir "C:/Navchannya/4.1/АПКС/RockPaperScissors/ServerCommunication"

    - name: Compile Arduino Sketch
      run: |
        arduino-cli compile --fqbn arduino:avr:uno "C:/Navchannya/4.1/АПКС/RockPaperScissors/ServerCommunication"

    # 6. Тестування C# проекту
    - name: Restore dependencies
      run: dotnet restore ArduinoClient/ArduinoClient.sln

    - name: Build project
      run: dotnet build ArduinoClient/ArduinoClient.sln --configuration Release

    - name: Run tests
      run: dotnet test ArduinoClient/ArduinoClient.sln --configuration Release --logger "trx"

    # 7. Завантаження прошивки (опціонально)
    - name: Upload Firmware to Arduino
      run: |
        arduino-cli upload --fqbn arduino:avr:uno --port COM5 "C:/Navchannya/4.1/АПКС/RockPaperScissors/ServerCommunication"

    # 8. Публікація артефактів
    - name: Publish build
      run: dotnet publish ArduinoClient/ArduinoClient.sln --configuration Release --output ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: ./publish

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: ./TestResults/*.trx
