name: Build and Test Arduino Client

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Navigate to project directory
      run: cd ArduinoClient

    - name: Restore dependencies
      run: dotnet restore ArduinoClient.csproj

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release --logger "trx"

    - name: Publish build
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: ./publish

    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: ./TestResults/*.trx
